### ISSUE TITLE
一直提示验证码错误，请求大神解决下问题，帮我挂到号

### ISSUE THREAD

**Issue by wkiii** [iBreaker/bjguahao#106]
##问题描述：
程序测试运行的时候，正常登陆后开始挂号，显示有号(网站上也是有号的)，但始终不能正常挂到号，一直提示手机验证码错误，错误反复出现。我手动输入过验证码，也用iMessage+mac 的方式自动输入验证码的方式，都是如下这样的错误。因为家里人生病需要挂号，所以请求大神帮忙解决下问题[拜托][拜托]  
###具体出错的日志如下：
Sun, 13 Oct 2019 17:46:18 bjguahao.py[line:375] INFO 当前号余量:
+------------+------+--------+
|  医生姓名  | 擅长 | 号余量 |
+------------+------+--------+
| 副主任医师 |      |   有   |
|   普通号   | None |   有   |
+------------+------+--------+
Sun, 13 Oct 2019 17:46:18 bjguahao.py[line:364] INFO 选中:副主任医师
Sun, 13 Oct 2019 17:46:18 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "GET /web/getVerifyCode?mobile=18210569660&smsKey=ORDER_CODE&rd=1570959978148 HTTP/1.1" 200 36
Sun, 13 Oct 2019 17:46:18 bjguahao.py[line:523] DEBUG {"resCode":0,"msg":null,"data":null}
Sun, 13 Oct 2019 17:46:18 bjguahao.py[line:525] INFO 获取验证码成功
sms_code: 470984
Sun, 13 Oct 2019 17:46:26 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "POST /web/order/saveOrder HTTP/1.1" 200 62
Sun, 13 Oct 2019 17:46:26 bjguahao.py[line:447] DEBUG payload:{"hospitalId": "166", "departmentId": "200040048", "dutySourceId": "64289438", "doctorId": "201173732", "patientId": "15766951", "dutyDate": "2019-10-18", "dutyCode": 1, "totalFee": 300, "period": "", "mapDepartmentId": "", "mapDoctorId": "", "planCode": "", "medicareCardId": "", "jytCardId": "", "hospitalCardId": "", "mapDutySourceId": "", "smsCode": "470984", "mobileNo": "1821056955x", "feeColor": "", "fcode": "", "dutyImgType": ""}
Sun, 13 Oct 2019 17:46:26 bjguahao.py[line:448] DEBUG response data:{"resCode":10000,"msg":"手机验证码错误！","data":null}
Sun, 13 Oct 2019 17:46:26 bjguahao.py[line:463] ERROR 手机验证码错误！
Sun, 13 Oct 2019 17:46:26 bjguahao.py[line:312] DEBUG 当前挂号日期: 2019-10-18
Sun, 13 Oct 2019 17:46:27 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "POST /web/product/detail HTTP/1.1" 200 1561
Sun, 13 Oct 2019 17:46:27 bjguahao.py[line:320] DEBUG response data:{"resCode":0,"msg":null,"data":[{"dutyCode":1,"dutyImgUrl":"//img.114yygh.com/fe/home/iconfont/1679091c5a880faf6fb5e6087eb1b2dc","dutyImgType":6,"detail":[{"dutySourceId":64289438,"doctorId":201173732,"mapDepartmentId":"3040101","mapDoctorId":"","doctorName":null,"doctorTitleName":"副主任医师","doctorSkill":"","mapDutySourceId":null,"dutyDate":"2019-10-18","dutyCode":1,"planCode":null,"dutyPeriod":[],"totalFee":70,"totalCount":19,"remainAvailableNumber114":18,"remainAvailableNumberWeb":17,"fcode":"&#xf46d;&#xf38a;","ncode":"&#xf170;","zcode":"&#xf38a;","wcode":"&#xf170;"},{"dutySourceId":64289386,"doctorId":201118442,"mapDepartmentId":"3040101","mapDoctorId":"","doctorName":null,"doctorTitleName":"普通号","doctorSkill":null,"mapDutySourceId":null,"dutyDate":"2019-10-18","dutyCode":1,"planCode":null,"dutyPeriod":[],"totalFee":200,"totalCount":1,"remainAvailableNumber114":8,"remainAvailableNumberWeb":15,"fcode":"&#xf3c2;&#xf38a;","ncode":"&#xf6b9;","zcode":"&#xf38a;","wcode":"&#xf6b9;"}]},{"dutyCode":2,"dutyImgUrl":"//img.114yygh.com/fe/home/iconfont/1679091c5a880faf6fb5e6087eb1b2dc","dutyImgType":6,"detail":[{"dutySourceId":64289388,"doctorId":201118442,"mapDepartmentId":"3040101","mapDoctorId":"","doctorName":null,"doctorTitleName":"普通号","doctorSkill":null,"mapDutySourceId":null,"dutyDate":"2019-10-18","dutyCode":2,"planCode":null,"dutyPeriod":[],"totalFee":80,"totalCount":25,"remainAvailableNumber114":14,"remainAvailableNumberWeb":31,"fcode":"&#xf3c2;&#xf38a;","ncode":"&#xf6b9;","zcode":"&#xf38a;","wcode":"&#xf6b9;"}]}]}
Sun, 13 Oct 2019 17:46:27 bjguahao.py[line:375] INFO 当前号余量:
+------------+------+--------+
|  医生姓名  | 擅长 | 号余量 |
+------------+------+--------+
| 副主任医师 |      |   有   |
|   普通号   | None |   有   |
+------------+------+--------+
Sun, 13 Oct 2019 17:46:27 bjguahao.py[line:364] INFO 选中:副主任医师
Sun, 13 Oct 2019 17:46:27 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "GET /web/getVerifyCode?mobile=18210569660&smsKey=ORDER_CODE&rd=1570959987040 HTTP/1.1" 200 36
Sun, 13 Oct 2019 17:46:27 bjguahao.py[line:523] DEBUG {"resCode":0,"msg":null,"data":null}
Sun, 13 Oct 2019 17:46:27 bjguahao.py[line:525] INFO 获取验证码成功
sms_code: 756675
Sun, 13 Oct 2019 17:46:35 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "POST /web/order/saveOrder HTTP/1.1" 200 62
Sun, 13 Oct 2019 17:46:35 bjguahao.py[line:447] DEBUG payload:{"hospitalId": "166", "departmentId": "200040048", "dutySourceId": "64289438", "doctorId": "201173732", "patientId": "15766951", "dutyDate": "2019-10-18", "dutyCode": 1, "totalFee": 70, "period": "", "mapDepartmentId": "", "mapDoctorId": "", "planCode": "", "medicareCardId": "", "jytCardId": "", "hospitalCardId": "", "mapDutySourceId": "", "smsCode": "756675", "mobileNo": "1821056955x", "feeColor": "", "fcode": "", "dutyImgType": ""}
Sun, 13 Oct 2019 17:46:35 bjguahao.py[line:448] DEBUG response data:{"resCode":10000,"msg":"手机验证码错误！","data":null}
Sun, 13 Oct 2019 17:46:35 bjguahao.py[line:463] ERROR 手机验证码错误！
Sun, 13 Oct 2019 17:46:35 bjguahao.py[line:312] DEBUG 当前挂号日期: 2019-10-18
Sun, 13 Oct 2019 17:46:35 connectionpool.py[line:437] DEBUG http://www.114yygh.com:80 "POST /web/product/detail HTTP/1.1" 200 1563

**Comment by JanonWang** [comment]
我也遇到了这样的情况，我是在linux上直接运行的挂号脚本，是不是网站的输入的验证码后面又进行加密啥的了？

**Comment by JanonWang** [comment]
但是比较奇怪的是，在登录时输入验证码是直接可以登录的，并没有出现验证码报错的情况

**Comment by JanonWang** [comment]
看到 #102 已经说解决了这个问题，但是我刚用最新版试了下，还是不太行，希望大神抽时间解决下

**Comment by iBreaker** [comment]
可能是接口又变了，最近过两天就变一次。我有空了抓包看下

**Comment by tobin4j** [comment]
我直接在web页面去操作预约也显示验证码错误,感觉就是线上的BUG

**Comment by tobin4j** [comment]
接口抓了一下看起来是没变

**Comment by iBreaker** [comment]
更新下代码试试？

**Comment by iBreaker** [comment]
代码已更新
