### ISSUE TITLE
挂号类型选择

### ISSUE THREAD

**Issue by iBreaker** [iBreaker/bjguahao#11]
可在配置文件中选择医保/自费等类型

**Comment by chinabuffon** [comment]
第一次输入的短信验证码经常会提示短信验证码错误~这个问题有没有碰到？

**Comment by iBreaker** [comment]
遇到过  还不清楚是什么原因

**Comment by coeusite** [comment]
这个在网站上好象是不能选的……
实际挂号类型可能跟患者在医院的档案类型有关。
同时，不同医院的政策可能不同。
