### ISSUE TITLE
pc上正常，android 9(小米6) aes加密模块报错，是不是得改引用库的源代码？

### ISSUE THREAD

**Issue by shamohai** [iBreaker/bjguahao#113]
![微信图片_20191104173224](https://user-images.githubusercontent.com/7419781/68111258-a811ed80-ff29-11e9-9cf0-90044e0943c5.jpg)

**Comment by iBreaker** [comment]
试着装一下这个库？

**Comment by shamohai** [comment]
要求的4个库都装了，还需要装哪个？python不是很熟

**Comment by iBreaker** [comment]
https://github.com/iBreaker/bjguahao/issues/92

**Comment by shamohai** [comment]
![20191105123919](https://user-images.githubusercontent.com/7419781/68179074-5456e100-ffc9-11e9-9b83-47690e2d5d8a.jpg)
上午卸载重装了python，现在只有pip3 安装 pycryptodome 报错，其他库正常。

**Comment by shamohai** [comment]
用QPYPI  安装跟上面 pip3 安装报同样的错误。

**Comment by iBreaker** [comment]
环境问题。非项目问题。😊
