### ISSUE TITLE
排除普通号，怎么设置啊？

### ISSUE THREAD

**Issue by ring0li** [iBreaker/bjguahao#114]
麻烦了

**Comment by niuliwei1029** [comment]
也或者比如口腔科包含：口腔黏膜副主任和牙科普通，我想挂牙科普通号。怎么设置呢？

**Comment by niuliwei1029** [comment]
`     简单实现了排除普通号的方法，着急的话可以借鉴。找到以下地方进行更改，大概在363行：
       # 若没有合适的医生，默认返回最好的医生
        for doctor in doctors:
            if doctor['doctorTitleName'] in ["口腔黏膜普通","普通号"]:
                pass
            else:
                if doctor['totalCount']%2 != 0:
                    logging.info("选中:" + self.get_doctor_name(doctor))
                    return doctor
        return "NoDuty"`

**Comment by iBreaker** [comment]
需要修改代码  可以修改后提交PR哦
