### ISSUE TITLE
可以用学校邮箱求一份吗

### ISSUE THREAD

**Issue by X-Bruce-Y** [iBreaker/bjguahao#123]
iBreaker大佬，看到最后两条#121#122 issue里您说因为有黄牛所以删了，非常理解。但我在app上挂号总是直接没号，迫不得已想到用爬虫，查到您写的这个工具，如果可以的话希望能发一份到xinyu.yang@pku.edu.cn，万分感谢！

**Comment by iBreaker** [comment]
几个月没有更新已经不能使用了  抱歉

**Comment by X-Bruce-Y** [comment]
没事没事，还是谢谢啦！-------- 原始邮件 --------发件人： Breaker <notifications@github.com>日期： 2020年5月28日周四 15:25收件人： iBreaker/bjguahao <bjguahao@noreply.github.com>抄送： Seikegn Yang <xinyu.yang@pku.edu.cn>, Author <author@noreply.github.com>主    题： Re: [iBreaker/bjguahao] 可以用学校邮箱求一份吗 (#123)

几个月没有更新已经不能使用了  抱歉

**Comment by iBreaker** [comment]
需要的话可以发给你以前的

**Comment by X-Bruce-Y** [comment]
哇，如果方便的话麻烦发我一份吧，我学习一下，感谢！-------- 原始邮件 --------发件人： Breaker <notifications@github.com>日期： 2020年5月28日周四 16:10收件人： iBreaker/bjguahao <bjguahao@noreply.github.com>抄送： Seikegn Yang <xinyu.yang@pku.edu.cn>, Author <author@noreply.github.com>主    题： Re: [iBreaker/bjguahao] 可以用学校邮箱求一份吗 (#123)

需要的话可以发给你以前的

**Comment by iBreaker** [comment]
已发送

**Comment by X-Bruce-Y** [comment]
收到了，感谢！祝好！-------- 原始邮件 --------发件人： Breaker <notifications@github.com>日期： 2020年6月2日周二 10:52收件人： iBreaker/bjguahao <bjguahao@noreply.github.com>抄送： Seikegn Yang <xinyu.yang@pku.edu.cn>, Author <author@noreply.github.com>主    题： Re: [iBreaker/bjguahao] 可以用学校邮箱求一份吗 (#123)

已发送
