### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by xaxfan** [iBreaker/bjguahao#126]
您好请教一下，好像这个挂号软件不能用了，看起来是接口变了，求问有新版吗

**Comment by iBreaker** [comment]
没有 已经停止更新了

**Comment by xaxfan** [comment]
能不能授人以渔😂，我要怎么找到新的接口呢

**Comment by xaxfan** [comment]
挂号实在是太难了

**Comment by xaxfan** [comment]
求加wx指教也行，787764871

**Comment by iBreaker** [comment]
你用的是哪个版本？可以发一份最后的那个版本给你

**Comment by xaxfan** [comment]
我自己copy的一份，所以不知道哪个版本了，最后的版本可以用吗？

**Comment by hhkbble** [comment]
@iBreaker 能给我一份吗，给我爸看病挂不上号

**Comment by Jiefwang** [comment]
@iBreaker 可以求一份吗，自用，网上、公众号上试了好些天都挂不上。🙏

**Comment by iBreaker** [comment]
[bjguahao.tar.gz](https://github.com/iBreaker/bjguahao/files/4720829/bjguahao.tar.gz)
@haoyixin hao @Jiefwang jie

**Comment by Jiefwang** [comment]
谢谢！

**Comment by zoucao** [comment]
大佬能不能发我一份，看病挂不上号呀，呜呜呜。

**Comment by gaohongfein** [comment]
请问现在能用么？只能用验证码登陆，返回
resCode | 10000
msg | "渠道非法"
data | null
，请问怎么解决？给老婆挂号，急

**Comment by zoucao** [comment]
> 请问现在能用么？只能用验证码登陆，返回
> resCode | 10000
> msg | "渠道非法"
> data | null
> ，请问怎么解决？给老婆挂号，急

作者已经不更新了，建议去目标医院的公众号或者app挂号，比那个平台好挂很多

**Comment by gaohongfein** [comment]
挂不上。。只能找黄牛了

**Comment by yaolinli** [comment]
> 挂不上。。只能找黄牛了

现在去哪里找黄牛哇？都变成线上app或者微信抢号了，根本抢不到专家号TT
