### ISSUE TITLE
还没放号问题

### ISSUE THREAD

**Issue by dienegit** [iBreaker/bjguahao#19]
快到放号时间开始运行脚本9:29，每秒重试一次，直到超过放号时间9:32，一直显示还没放号。强行结束程序9:32，重启程序9:32，此时才显示医生列表，但是号早已被挂完。。。
难道select_doctor过程有缓存？看起来又不像，很奇怪，不知道有没有其他人遇到详细问题？眼睁睁错过放号时间但程序始终显示没放号。
运行环境win7 cmd

**Comment by iBreaker** [comment]
放号时间不是固定的九点半，每次都会有一些时间偏差。应该是挂号网站的系统就是那么设计的。强行关闭和启动，之间有多长时间？

**Comment by dienegit** [comment]
我在跑脚本的同时，用浏览器打开挂号网页，大概9:31上面显示已经放号并全部约满，但是脚本依然显示没放号，继续重试中。9:32我才关闭和重启程序，中间也就几秒钟。重启后就能正确显示医生列表和无号状态了。

**Comment by iBreaker** [comment]
web上已经看到放好了？

**Comment by iBreaker** [comment]
我没有遇到过这样的，医院和科室方便提供下吗

**Comment by dienegit** [comment]
就是北医三院的运动医学

**Comment by iBreaker** [comment]
我前两天还挂到了一个科室的

**Comment by dienegit** [comment]
请问你是什么运行环境？

**Comment by iBreaker** [comment]
linux  py 2.7

**Comment by dienegit** [comment]
我明天加点log输出看看。还有个问题，验证码现在还可以提前获取吗？我看你改过逻辑，以前是先拿验证码再挂号。

**Comment by iBreaker** [comment]
config 里面调成debug 能看到详细日志。验证码提前获取，试了下会提示验证码错误。你可以再试试

**Comment by dienegit** [comment]
看来验证码是改进了

**Comment by iBreaker** [comment]
这个还不能确定，不提前获取验证码可以挂到，就没有在仔细看提前获取验证码的了

**Comment by happier2** [comment]
现在还可以提前获取验证码吗？是不是挂号平台已经改进了？

**Comment by iBreaker** [comment]
没有做提前获取验证码

**Comment by smartyaya** [comment]
遇到同样的问题。
