### ISSUE TITLE
验证码错误

### ISSUE THREAD

**Issue by wangxiaobupt** [iBreaker/bjguahao#2]
我获得验证码之后，在输入框输入验证码时会显示验证码错误。不知道是不是这个流程不对，想问一下验证码是在什么时候获取比较好，我这边是把验证码获取放到刷到号之后发送，还是会显示验证码错误。

**Comment by yiqian987** [comment]
请问 我这直接在linux下执行 python bjguahao.py就卡住不动了，是为何？

**Comment by wangxiaobupt** [comment]
你是没改代码吧，里面东西都改了没

**Comment by iBreaker** [comment]
最近网站做过一次更新，流程有些变化，应该是不能成功挂号了。过段时间有可能会重新写下代码，同时也欢迎各位修改代码

**Comment by wangxiaobupt** [comment]
接口都是自己抓的么，我最近准备尝试一下。

**Comment by iBreaker** [comment]
是自己抓包分析的

**Comment by yiqian987** [comment]
目前尝试了一下 可以正常挂号，但是对于验证码错误的问题  是由于send_msg_code方法写在了auth_login()后面，这样一登录就会产生一条登陆短信密码。屏蔽之后测试还是不会发送密码，发现是由于send_msg_code方法写在了raw_input后面，程序一直等待输入，未执行方法所以不发送验证码。不知道说的对不对，欢迎敲砖哈，自己稍微改了下main方法下的代码，加星号的地方是修改的位置，现在挂号是正常的。

PS： 如果一个账号下有3 4个患者的话，如何选择非最后一个添加的候选人？还有医生如何自定义选择，而非只能选择最后的一个专家或者医生？
```
def main():
    urlOpener = auth_login()
**#    send_msg_code(urlOpener)**
    while True:
        while True:
            ids = get_ids(urlOpener)
            if ids == -2:
                exit("今天没有号了")
            elif ids == -1:
                print "号还未放出, 等待..."
                time.sleep(5)         #号还没有产生，sleep 5秒
                continue
            else:
                break
        patientId = get_patientId(urlOpener, ids)
        **send_msg_code(urlOpener)**
        msg_code = raw_input("输入短信验证码: ")
        fuck(urlOpener, ids, patientId, msg_code)
        **#send_msg_code(urlOpener)**
```

**Comment by yiqian987** [comment]
还有一个问题，在linux下死活不能运行，会夯住  win下没问题 但是有乱码，我在头部添加了
```
import sys
sys.getdefaultencoding()
reload(sys)
sys.setdefaultencoding('UTF-8')
sys.getdefaultencoding()
```

**Comment by wangxiaobupt** [comment]
一登录就发验证码那里确实有问题，我之前把发送验证码放到patientId = get_patientId(urlOpener, ids)前了，发现出现验证码错误，今天分析了一下流程还是应该放到这句后面，准备明天看看效果。

医生的自定义选择在get_ids方法里面，默认的实现是选第一个有号的医生，可以改里面的实现。
患者的选择在get_patientId这个方法里。
linux下的乱码应该加一句  # -*- coding: utf-8 应该就好了

**Comment by iBreaker** [comment]
改好了发Pull Reauests

**Comment by iBreaker** [comment]
这个脚本本来是做来自己用的 所以没有考虑很多产品化的东西，所以在使用上可能很不友好。 后面慢慢改进

**Comment by iBreaker** [comment]
候选人需要独立出来，登陆后要读取候选人列表，让用户可以有选择的操作

**Comment by iBreaker** [comment]
最新版本未复现~  fix
