### ISSUE TITLE
就诊人内有儿童的会挂号失败

### ISSUE THREAD

**Issue by yiqian987** [iBreaker/bjguahao#20]
![image](https://user-images.githubusercontent.com/20719472/26864553-64c38a74-4b8b-11e7-8e0d-3ebb4a9f9bec.png)
最近在就诊人里添加了一个儿童，，挂了儿研所的号，儿研所的挂号界面是这样婶儿的。。。。苦恼

**Comment by iBreaker** [comment]
挂不上吗

**Comment by yiqian987** [comment]
挂的时候会提示[0;31m 2017-06-07 14:00:17 [error] 患儿姓名不能为空！[0m
好吧，我自己改了下 ，现在已经可以搞了  不过没写到一个文件里。
我觉得可以加个判断写在一个文件里
log文件我起了一个config-children.json的文件增加了3个参数，其实可以加到config.json里。因为有些参数是空的也不影响

```
        "childrenName":"",
        "cidType":"1",
        "childrenIdNo":"",
```

挂号的主程序我单独起了一个bjguahao-children.py，不过也可以通过判断childrenName是否为空来进行下面的  preload 选取（不判断，无脑全部提交所有数据没试，不知道能不能成功）
顺便修复了下提示输入验证码乱码的问题

```
return raw_input("输入短信验证码: ")
改为
return raw_input("输入短信验证码: ".decode('utf-8').encode('gbk'))
```

config类里增加了如下内容
class Config(object):

    def __init__(self):
        self.childrenName = ""
        self.cidType = ""
        self.childrenIdNo = ""

    def load_conf(self):
        try:
            with open('config-children.json') as json_file:
                self.childrenName = data["childrenName"]
                self.cidType = data["cidType"]
                self.childrenIdNo = data["childrenIdNo"]

                Log.debug("患儿姓名:" + str(self.childrenName))
                Log.debug("患儿证件:" + str(self.cidType))
                Log.debug("患儿证件号码:" + str(self.childrenIdNo))

class Guahao(object):类里修改

```
    def get_it(self, doctor, sms_code):

        childrenName = self.config.childrenName
        cidType = self.config.cidType
        childrenIdNo = self.config.childrenIdNo

        preload = {

            'childrenName': childrenName,
            'cidType': cidType,
            'childrenIdNo': childrenIdNo,
	'isAjax': True
        }

```

**Comment by iBreaker** [comment]
要是有修改，可以Pull requests，欢迎提交代码

**Comment by iBreaker** [comment]
暂不打算支持
