### ISSUE TITLE
验证码错误的问题复现

### ISSUE THREAD

**Issue by yiqian987** [iBreaker/bjguahao#21]
今天中午又挂了一下号，昨天解决了儿童挂号缺少信息的问题，今天挂号 第一个验证码下发下来输入之后会提示验证码错误，接着第二次请求，验证码输入无问题成功挂到号。
朋友挂北医三院的时候也遇到过验证码第一次不正确，甚至第二次都不正确的问题。
同样的  不用去抢的号，或者很多时间点都有号的科室，第一个验证码肯定正确。
看了下代码 没有思路，不知道是啥问题。你有什么思路么？

**Comment by coeusite** [comment]
我只碰到过第一次不对的情况，第二次就正常了。

感觉是服务器逻辑的问题。

**Comment by iBreaker** [comment]
还有人遇到过这样的问题吗

**Comment by zpk2017** [comment]
嗯，我刚刚也遇到这个问题，先是一直发送过来的验证码输入后会报：[error] ValueError('No JSON object could be decoded',)  这个错误，然后重复输入几次后，会先是短信发送太频繁，exit。

**Comment by iBreaker** [comment]
有没有保留详细日志

**Comment by zpk2017** [comment]
```
2017-07-27 10:35:56 [info] DebugLevel设置为:2                       
│ 2017-07-27 10:35:56 [info] 配置加载完成                             
│ 2017-07-27 10:35:57 [info] 今日可挂号到: 2017-08-03                 
│ 2017-07-27 10:35:57 [info] 放号时间: 2017-07-24 08:30               
│ 2017-07-27 10:35:57 [info] 开始登陆                                 
│ 2017-07-27 10:35:57 [info] 登陆成功                                 
2017-07-27 10:35:57 [info] 当前号余量:                              
│+----------+--------------+--------+                                 
| 医生姓名 |     擅长     | 号余量 |                                 
│+----------+--------------+--------+                                 
│| 主治医师 |    营养科    |   1    |                                 
│| 主治医师 | 孕期营养门诊 |   1    |                                 
+----------+--------------+--------+                                 
│ 2017-07-27 10:35:57 [info] 选中:主治医师                            
│ 2017-07-27 10:35:57 [info] 获取验证码成功                           
│输入短信验证码: 701776            
│ 2017-07-27 10:36:16 [info] 病人ID:233376388                         
│ 2017-07-27 10:36:17 [error] ValueError('No JSON object could be deco
│ded',)           
│ 2017-07-27 10:36:18 [info] 当前号余量:                              
│+----------+--------------+--------+                                 
│| 医生姓名 |     擅长     | 号余量   |                                 

│+----------+--------------+--------+                                 
│| 主治医师 |    营养科    |   1    |                                 
│| 主治医师 | 孕期营养门诊 |   1    |                                 
│+----------+--------------+--------+                                 
│ 2017-07-27 10:36:18 [info] 选中:主治医师                            
│ 2017-07-27 10:36:18 [info] 获取验证码成功                           
│输入短信验证码:  

```

以上就是。然后一直输入验证码都是那个提示，最后提示验证码输入次数过多，退出。

**Comment by zpk2017** [comment]
输入的验证码是怎么处理的啊，看提示是没有读取到json对象啊。

**Comment by iBreaker** [comment]
def get_sms_verify_code(self):
        """获取短信验证码"""
        response = self.browser.post(self.send_code_url, "")
        data = json.loads(response.text)
        Log.debug(response.text)
        if data["msg"] == "OK." and data["code"] == 200:
            Log.info("获取验证码成功")
            return raw_input("输入短信验证码: ")
        elif data["msg"] == "短信发送太频繁" and data["code"] == 812:
            Log.exit(data["msg"])
        else:
            Log.error(data["msg"])
            return None

**Comment by iBreaker** [comment]
可能返回的不是json格式的吧

**Comment by zpk2017** [comment]
等下啊 我设置下debug试试

**Comment by iBreaker** [comment]
直接把response.text打印出来吧  看看出错的时候到底是啥

**Comment by coeusite** [comment]
实测，当遭遇502返回时后出现这个错误
`ValueError('No JSON object could be decoded',)`

**Comment by iBreaker** [comment]
挂号时候出现的问题吧？  把日志打印出来看看

**Comment by coeusite** [comment]
（并没有看到 response.txt）扫了一眼log，是电脑上的 Privoxy 挂掉了……
``` 
2017-08-03 08:35:02 [debug] response data:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>

<head>
  <title>502 - No server or forwarder data received (Privoxy@localhost.localdomain)</title>
（略） 

</html>

 2017-08-03 08:35:02 [error] ValueError('No JSON object could be decoded',)
 2017-08-03 08:35:02 [error] exit
```

**Comment by iBreaker** [comment]
这是什么时候的日志  登录吗？

**Comment by coeusite** [comment]
上一条是查询余号。时间的话，是因为我还原了一下虚拟机
虽然应该和zpk2017的不同，但我想ta那边可能也是502、503什么的
```
2017-08-02 10:02:16 [debug] post data :{'dutyCode': u'1', 'dutyDate': u'2017-08-16', 'hospitalId': u'133', 'departmentId': u'200001346', 'isAjax': True}
```

**Comment by iBreaker** [comment]
你登陆成功了？  前天登录的地址都换了诶，我还没来得及抓包分析。怎么登陆上去的呢？你做过修改吗

**Comment by iBreaker** [comment]
https://github.com/iBreaker/bjguahao/issues/24

**Comment by coeusite** [comment]
貌似登陆成功……

```
 2017-08-03 09:28:59 [info] 登陆成功
 2017-08-03 09:28:59 [info] 距离放号时间还有1860.097464秒
 2017-08-03 09:28:59 [info] 程序休眠1800.097464秒后开始运行
```

**Comment by coeusite** [comment]
新的url: `http://www.bjguahao.gov.cn/tologin.htm`

**Comment by iBreaker** [comment]
http://www.bjguahao.gov.cn/tologin.htm  这个地址可以登录成功吗？ 测一下呗，要是可以的话，提交Pull requests  ;-)  和之前的登录界面看起来是一样的，应该问题不大

**Comment by coeusite** [comment]
登录不成功，返回值是HTML，而非JSON。

**Comment by iBreaker** [comment]
刚才测了下 http://www.bjguahao.gov.cn/quicklogin.htm  发现这个链接正常，可以用的

**Comment by coeusite** [comment]
我这里不可以用，Chrome访问显示404
使用脚本可以用这个URL登录，但是在挂号时会提示
`2017-08-03 10:03:13 [debug] response data:{"data":],"hasError":true,"code":2009,"msg":"用户未登录!"}`

**Comment by iBreaker** [comment]
麻烦贴上**所有的**debug的日志，贴日志前**吧身份有关的信息去掉即可**，**要么无法确定问题**

**Comment by coeusite** [comment]
呃……现在我这里也可以使用了（尴尬

```
$ python2 bjguahao.py
 2017-08-03 11:28:47 [info] DebugLevel设置为:1
 2017-08-03 11:28:47 [debug] DebugTest
 2017-08-03 11:28:47 [info] 配置加载完成
 2017-08-03 11:28:47 [debug] 手机号:
 2017-08-03 11:28:47 [debug] 挂号日期:latest
 2017-08-03 11:28:47 [debug] 医院id:133
 2017-08-03 11:28:47 [debug] 科室id:200001346
 2017-08-03 11:28:47 [debug] 上午/下午:1
 2017-08-03 11:28:47 [debug] 就诊人姓名:***
 2017-08-03 11:28:47 [info] 今日可挂号到: 2017-08-17
 2017-08-03 11:28:47 [info] 当前挂号日期变更为: 2017-08-17
 2017-08-03 11:28:47 [info] 放号时间: 2017-08-03 10:00
 2017-08-03 11:28:47 [info] 开始登陆
 2017-08-03 11:28:47 [debug] post data :{'isAjax': True, 'password': u'***', 'mobileNo': u'***', 'yzm': ''}
 2017-08-03 11:28:48 [debug] response data:{"data":[],"hasError":false,"code":200,"msg":"OK"}
 2017-08-03 11:28:48 [info] 登陆成功
 2017-08-03 11:28:48 [debug] 当前挂号日期: 2017-08-17
 2017-08-03 11:28:48 [debug] post data :{'dutyCode': u'1', 'dutyDate': u'2017-08-17', 'hospitalId': u'133', 'departmentId': u'200001346', 'isAjax': True}
 2017-08-03 11:28:48 [debug] response data:{"data":[{"dutySourceId":46907446,"portrait":" pic/zhuanjia.gif","doctorName":"普通医师","doctorTitleName":"普通医师","skill":"牙龈出血、口臭、牙齿松动移位、洗牙、牙周手术","totalFee":50.0,"remainAvailableNumber":0,"dutySourceStatus":1,"hospitalId":133,"departmentId":"200001346","doctorId":"200352984","drCode":null,"planCode":null,"dutyDate":null,"dutyCode":null,"departmentName":null,"isShowFee":2,"dlDutySources":null,"morningnum":0,"afternoonnum":0,"majorName":null,"majorIntroduce":null,"dldutyDate":null,"dldutyCode":null,"regNo":0}],"hasError":false,"code":200,"msg":"OK"}
 2017-08-03 11:28:48 [info] 当前号余量:
+----------+----------------------------------------------+--------+
| 医生姓名 |                     擅长                     | 号余量 |
+----------+----------------------------------------------+--------+
| 普通医师 | 牙龈出血、口臭、牙齿松动移位、洗牙、牙周手术 |   0    |
+----------+----------------------------------------------+--------+
 2017-08-03 11:28:48 [error] 没号了,  亲~
```

**Comment by iBreaker** [comment]
恩恩 那就好  。洗牙在医保范围内吗

**Comment by coeusite** [comment]
不在。

**Comment by iBreaker** [comment]
那座城市？

**Comment by yiqian987** [comment]
现在你们确认能挂号么？我这边刚刚找了一个医院随便试了一下，也是返回
 2017-08-03 23:57:57 [error] ValueError('No JSON object could be decoded',)
不知是哪里出了问题

**Comment by yiqian987** [comment]
现在获得了短信验证码后调试模式抓到的preview是
```
{data: [], hasError: true, code: 7001, msg: "短信验证码错误!"}
code:7001
data:[]
hasError:true
msg:"短信验证码错误!"
```
response如下
{"data":[],"hasError":true,"code":7001,"msg":"短信验证码错误!"}

**Comment by iBreaker** [comment]
调到debug模式可以看到返回的内容不是json是什么。   贴日志的时候最好把所有的日志都贴出来，只有一行什么也看不出来。

**Comment by yiqian987** [comment]
调试的日志就是返回了一个html页面，其他没有任何有用的信息。
此外我发现现在在提交确认的时候似乎多post了一个字段
dutySourceId=46914346  这个字段之前是没有的吧？
下面是完成的post数据
dutySourceId=46914346&hospitalId=102&departmentId=200039730&doctorId=201125970&patientId=****&jytCardId=&medicareCardId=&reimbursementType=1&smsVerifyCode=959547&childrenName=***&cidType=1&childrenIdNo=***&childrenBirthday=2011-07-03&childrenGender=2&isAjax=true

**Comment by yiqian987** [comment]
这是我在网页上成功挂号后http://www.bjguahao.gov.cn/order/confirm.htm
post的信息dutySourceId=46914346&hospitalId=102&departmentId=200039730&doctorId=201125970&patientId=****&jytCardId=&medicareCardId=&reimbursementType=-1&smsVerifyCode=935445&childrenName=****&cidType=1&childrenIdNo=****&childrenBirthday=2011-07-03&childrenGender=2&isAjax=true
页面给我返回的response内容
{"data":[{"hospitalName":"首都儿科研究所附属儿童医院","departmentName":"中医科门诊","patientName":"***","idTypeName":"身份证","patientIdNo":"***","recognitionCode":"***","dutyDate":"2017-08-10","dutyCode":2,"ampm":"下午","offerTime":"下午号11:30-14:30,过时作废","offerAddress":"就诊当日须出示患儿的有效证件（户口本/身份证/护照/港澳通行证/台胞证），及医保卡或京医通卡至114预约取号窗口取号，无京医通卡患儿可到门诊大厅建卡中心办理京医通卡后至114预约挂号窗口取号就诊","numericalSequence":"33","temporalSequence":"03","needTs":true,"needNs":true}],"hasError":false,"code":200,"msg":"OK"}
preview内容如下
{,…}
code:200
data:[{hospitalName: "首都儿科研究所附属儿童医院", departmentName: "中医科门诊", patientName: "***", idTypeName: "身份证",…}]
0:{hospitalName: "首都儿科研究所附属儿童医院", departmentName: "中医科门诊", patientName: "***", idTypeName: "身份证",…}
hasError:false
msg:"OK"

**Comment by iBreaker** [comment]
加群  637662992交流吧，这里讨论效率太低了

**Comment by iBreaker** [comment]
挂号返回html的问题已经解决，回归主题，目前验证码有时候不生效的问题不能稳定复现。继续观察

**Comment by gqk289** [comment]
+1

遇到类似的问题，描述一下：

使用 Mac 接收验证码，在预定放号时间前 30s 可以获取验证码，但是预约时显示不在预约周期内，再重复一次 response 仍是这个，在之后 response 为 验证码错误，重复几次验证码错误之后会显示发送验证码太频繁，之后程序退出。

日志如下：

`Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:211] DEBUG 当前挂号日期: 2018-09-11
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /dpt/partduty.htm HTTP/1.1" 200 555
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:222] DEBUG response data:{"data":[{"dutySourceId":56706774,"portrait":"","doctorName":"黎远皋","doctorTitleName":"知名专家","skill":"牙体牙髓病、根管治疗","totalFee":100.0,"remainAvailableNumber":2,"dutySourceStatus":1,"hospitalId":142,"departmentId":"200039542","doctorId":"201160812","drCode":null,"planCode":null,"dutyDate":null,"dutyCode":null,"departmentName":null,"isShowFee":1,"dlDutySources":null,"morningnum":0,"afternoonnum":0,"majorName":null,"majorIntroduce":null,"dldutyDate":null,"dldutyCode":null,"regNo":0}],"hasError":false,"code":200,"msg":"OK"}
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:253] INFO 当前号余量:
+----------+----------------------+--------+
| 医生姓名 |         擅长         | 号余量 |
+----------+----------------------+--------+
|  黎远皋  | 牙体牙髓病、根管治疗 |   2    |
+----------+----------------------+--------+
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:247] INFO 选中:黎远皋
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "GET /order/confirm/142-200039542-201160812-56706774.htm HTTP/1.1" 200 None
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:322] INFO 病人ID:
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:28 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /v/sendorder.htm HTTP/1.1" 200 24
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:363] DEBUG {"code":200,"msg":"OK."}
Tue, 04 Sep 2018 06:59:28 bjguahao.py[line:365] INFO 获取验证码成功
验证码: Tue, 04 Sep 2018 06:59:38 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:38 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /order/confirm.htm HTTP/1.1" 200 58
Tue, 04 Sep 2018 06:59:38 bjguahao.py[line:286] DEBUG response data:{"code":403,"hasError":true,"msg":"不在预约周期内"}
Tue, 04 Sep 2018 06:59:38 bjguahao.py[line:294] ERROR 不在预约周期内`

以及：

`Tue, 04 Sep 2018 06:59:46 bjguahao.py[line:211] DEBUG 当前挂号日期: 2018-09-11
Tue, 04 Sep 2018 06:59:46 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:47 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /dpt/partduty.htm HTTP/1.1" 200 555
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:222] DEBUG response data:{"data":[{"dutySourceId":56706774,"portrait":"","doctorName":"黎远皋","doctorTitleName":"知名专家","skill":"牙体牙髓病、根管治疗","totalFee":100.0,"remainAvailableNumber":2,"dutySourceStatus":1,"hospitalId":142,"departmentId":"200039542","doctorId":"201160812","drCode":null,"planCode":null,"dutyDate":null,"dutyCode":null,"departmentName":null,"isShowFee":1,"dlDutySources":null,"morningnum":0,"afternoonnum":0,"majorName":null,"majorIntroduce":null,"dldutyDate":null,"dldutyCode":null,"regNo":0}],"hasError":false,"code":200,"msg":"OK"}
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:253] INFO 当前号余量:
+----------+----------------------+--------+
| 医生姓名 |         擅长         | 号余量 |
+----------+----------------------+--------+
|  黎远皋  | 牙体牙髓病、根管治疗 |   2    |
+----------+----------------------+--------+
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:247] INFO 选中:黎远皋
Tue, 04 Sep 2018 06:59:47 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:47 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "GET /order/confirm/142-200039542-201160812-56706774.htm HTTP/1.1" 200 None
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:322] INFO 病人ID:
Tue, 04 Sep 2018 06:59:47 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 06:59:47 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /v/sendorder.htm HTTP/1.1" 200 24
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:363] DEBUG {"code":200,"msg":"OK."}
Tue, 04 Sep 2018 06:59:47 bjguahao.py[line:365] INFO 获取验证码成功
验证码: Tue, 04 Sep 2018 07:00:17 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 07:00:19 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /order/confirm.htm HTTP/1.1" 200 70
Tue, 04 Sep 2018 07:00:19 bjguahao.py[line:286] DEBUG response data:{"data":[],"hasError":true,"code":7001,"msg":"短信验证码错误!"}
Tue, 04 Sep 2018 07:00:19 bjguahao.py[line:294] ERROR 短信验证码错误!`

以及：

`Tue, 04 Sep 2018 07:00:21 connectionpool.py[line:243] DEBUG Resetting dropped connection: www.bjguahao.gov.cn
Tue, 04 Sep 2018 07:00:21 connectionpool.py[line:396] DEBUG http://www.bjguahao.gov.cn:80 "POST /v/sendorder.htm HTTP/1.1" 200 42
Tue, 04 Sep 2018 07:00:21 bjguahao.py[line:363] DEBUG {"code":812,"msg":"短信发送太频繁"}
Tue, 04 Sep 2018 07:00:21 bjguahao.py[line:374] ERROR 短信发送太频繁`
