### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by syzyyp** [iBreaker/bjguahao#24]
![default](https://user-images.githubusercontent.com/29562742/28769427-0d23bb56-760e-11e7-9d47-4becf6ecb3b2.png)

**Comment by iBreaker** [comment]
你的日志后面为什么有一些其他的东西

**Comment by syzyyp** [comment]
http://www.bjguahao.gov.cn/quicklogin.htm这个网址挂了显示404是不是这个原因

**Comment by iBreaker** [comment]
是的 ....  难道是改了登录地址？ 233333

**Comment by iBreaker** [comment]
现在还是这样吗？  不知道你是否可以重新抓包，找到登录地址。让脚本继续跑起来

**Comment by iBreaker** [comment]
改好后merge你的代码到主分支上

**Comment by syzyyp** [comment]
找到问题了，是我放在中文目录下面出现的问题，不能放在中文目录下面运行

**Comment by iBreaker** [comment]
你说的是乱码的问题？

**Comment by iBreaker** [comment]
#21

**Comment by iBreaker** [comment]
测试后确定链接没有变，404是因为不能用浏览器以GET的方式打开，问题解决
