### ISSUE TITLE
关于验证码提前获取问题

### ISSUE THREAD

**Issue by happier2** [iBreaker/bjguahao#29]
记得去年9月份自己也写过脚本去挂号，当时有一个小trick，验证码可以提前一分钟获取，这样只要查到号源信息，麻烦可以发起confirm，我看代码里面是查询到后才发验证码，现在是不能用提前获取验证码方法了？

**Comment by iBreaker** [comment]
想到过这个方法，但是不提前获取验证码也抢到了我想要的号，就没有实现这个功能。
