### ISSUE TITLE
脚本只会选取上午的号？下午有号也不会挂？

### ISSUE THREAD

**Issue by yiqian987** [iBreaker/bjguahao#3]
脚本只会选取上午的号？下午有号也不会挂？
今天挂，发现号源特别少，貌似只有上午
![image](https://cloud.githubusercontent.com/assets/20719472/23732106/1637fdfc-04ac-11e7-88dc-13138ab26f88.png)

**Comment by iBreaker** [comment]
dutyCode参数控制早上还是下午 dutyCode=1是早上 dutyCode=2是下午  代码中写死了  准备拿出来

**Comment by yiqian987** [comment]
我看看能不能改成3就全天轮寻一遍挂，那样挂到专家号的几率大点


发自我的 iPad

在 2017年3月9日，17:15，Breaker <notifications@github.com<mailto:notifications@github.com>> 写道：


dutyCode参数控制早上还是下午 dutyCode=1是早上 dutyCode=2是下午 代码中写死了 准备拿出来

**Comment by iBreaker** [comment]
3应该不可以吧，你试试。可以设置上午或者下午或者全天，全天的话两个循环都跑一遍就可以了

**Comment by iBreaker** [comment]
config 增加了配置上午或者下午的参数
