### ISSUE TITLE
departmentid map

### ISSUE THREAD

**Issue by haoyudong** [iBreaker/bjguahao#36]
如果想要挂某一科室，但不知道departmentID怎么办？ 有没有这样一个mapping，自动的根据科室中文名称map到ID？
以及是不是指定某个特定专家的号，这个需求应该比较大

**Comment by iBreaker** [comment]
打开这个科室的页面，url里面有科室哦。也可以做成一个mapping

**Comment by iBreaker** [comment]
有能力修改的话可以贡献代码哦，欢迎加入qq群交流。qq群在首页readme
