### ISSUE TITLE
关于运行脚本的问题

### ISSUE THREAD

**Issue by bumblebeecode** [iBreaker/bjguahao#45]
代码白痴，不知道如何运行脚本，未抢到号，操作如下：
环境：python 2.7
步骤：1.修改json文件，保存
           2.命令行输入 python2 bjguahao.py，出错，错误为IOError
           3.命令行输入 python2 bjguahao.py -c test.json，错误如上
           4.命令行再次输入python2 bjguahao.py,此时显示配置已完成开始登陆，然而还是出错，错误为用户不存在，登陆失败
           5.重复步骤4，一直到9点30登陆网页挂号界面显示已约满
求问大佬如何运行脚本。。。

**Comment by iBreaker** [comment]
加群把  首页有

**Comment by corleonegfw** [comment]
群主 已经申请加群 请审批 谢谢
