### ISSUE TITLE
【已解决】关于脚本运行

### ISSUE THREAD

**Issue by gifzlh** [iBreaker/bjguahao#46]
你好，感谢分享脚本。第一次运行，如下提示：  期盼有空时回复，万分感谢！
![22](https://user-images.githubusercontent.com/34907350/34404637-d02ad07a-ebe9-11e7-80cb-c7a1b76ccab5.JPG)
![gif](https://user-images.githubusercontent.com/34907350/34404638-d05c498e-ebe9-11e7-84b7-b0f64f315d2e.JPG)

**Comment by iBreaker** [comment]
你好  请使用python2

**Comment by gifzlh** [comment]
好的 万分感谢 我装的确实是python3版本

**Comment by gifzlh** [comment]
你好，我会第一时间回馈，如果一直没有回馈，很大概率应该是我一直不能搞定windows7系统下python双版本共存切换使用。

**Comment by gifzlh** [comment]
你好，已配置好python2版本，运行后如下提示：
![cmd](https://user-images.githubusercontent.com/34907350/34429760-7940c1ee-ec97-11e7-90cb-7ec5b634bb55.JPG)
![263](https://user-images.githubusercontent.com/34907350/34429762-818c25fa-ec97-11e7-9d85-1c87d77f944a.JPG)
![286](https://user-images.githubusercontent.com/34907350/34429763-87279c1a-ec97-11e7-94f1-9646953dd955.JPG)
![331-332](https://user-images.githubusercontent.com/34907350/34429765-8bb5a290-ec97-11e7-9016-d64a9ad70c19.JPG)
【纯代码小白，问题有点多，见谅】

**Comment by iBreaker** [comment]
你设置挂号时间了吗

**Comment by gifzlh** [comment]
感恩，好象成功了（日期被我留空处理了，太粗心，没仔细看页面提供的配置帮助文档）。测试用的配置文件默认的医院和科室id。前天上午手动给家里人挂的号，下周可以用这个试一下。刚刚试了下，因为没号了，所以不太清楚有号源的情况下，后续的操作，可能还需要磨合几次才能充分利用这么好的工具，再次感谢提供这么方便的脚本和耐心的解答，祝好运！
![cmd](https://user-images.githubusercontent.com/34907350/34432487-9f4859e0-ecb2-11e7-8acc-08d133b144de.JPG)

**Comment by iBreaker** [comment]
不客气  已经加了日期的验证，不会出现因为日期没有填写导致的问题，有兴趣的话可以加qq群交流
