### ISSUE TITLE
中国人民解放军总医院(301医院)—心血管内科 报错

### ISSUE THREAD

**Issue by iBreaker** [iBreaker/bjguahao#47]
Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:106] INFO 开始检查是否已经登录
Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:141] INFO cookies登录成功
Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:221] INFO 当前号余量:
+----------------+------------------------------------------------------------------------------------------------------+--------+
|    医生姓名    |                                                 擅长                                                 | 号余量 |
+----------------+------------------------------------------------------------------------------------------------------+--------+
|     心内科     |                                       心血管内科常见病的诊治。                                       |   2    |
| 难治高血压门诊 |                                       心血管内科常见病的诊治。                                       |   1    |
|      张然      | 冠心病、心力衰竭、心律失常和高血压病的诊断和治疗，主要从事冠心病的介入诊断和治疗，以及围手术期管理。 |   1    |
|     李玉峰     |             擅长难治性高血压，高脂血症，频发室性早搏，冠心病等各种原因引起的胸痛的诊治。             |   1    |
|     侯允天     |                           擅长高血压，心律失常，冠心病，代谢综合征的诊治。                           |   1    |
|      白静      |   擅长缺血性胸闷、胸痛的诊治；心肌梗死的急诊介入及长期药物治疗；冠脉病变、支架内再狭窄的介入治疗。   |   1    |
|     晏沐阳     |                                        心血管内科疾病的诊治。                                        |   1    |
|     陈光辉     |   擅长冠心病、肾动脉狭窄的介入诊断与治疗和高血压、血脂异常以及各种原因引起心衰等心血管疾病的诊治。   |   0    |
|     张志寿     |                         冠心病、高血压病、心脏瓣膜病、心肌病心律失常的诊治。                         |   0    |
|      王禹      |                    擅长复杂冠心病及肾、髂动脉狭窄的介入治疗及冠心病综合药物治疗。                    |   2    |
|     孙志军     |           擅长冠心病及肾动脉狭窄的介入治疗，难治性高血压诊治，过敏体质病人介入检查和治疗。           |   1    |
|     刘秀云     |                           冠心病、心肌梗塞、心律失常、高血压等疾病的诊治。                           |   1    |
|     李小鹰     |                          冠心病、高血压、心肌病、心力衰竭、心律失常的诊治。                          |   0    |
+----------------+------------------------------------------------------------------------------------------------------+--------+
Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:211] INFO 选中:***
Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:289] INFO 病人ID:***
输入短信验证码: Mon, 01 Jan 2018 16:56:07 bjguahao.py[line:332] INFO 获取验证码成功
413147
Mon, 01 Jan 2018 16:56:24 bjguahao.py[line:262] ERROR 亲属姓名不能为空！

**Comment by iBreaker** [comment]
报错亲属姓名不能为空  可能是默写医院有特殊的字段需要填写

**Comment by lmcl90** [comment]
301挂号规则：
①首次预约患者,预约时必须填写“亲属姓名”用于建档备查，首次填写后无需再填写；

**Comment by iBreaker** [comment]
> 301挂号规则：
> ①首次预约患者,预约时必须填写“亲属姓名”用于建档备查，首次填写后无需再填写；

👍
