### ISSUE TITLE
mac 下用 iMessage 读验证码可能有权限问题

### ISSUE THREAD

**Issue by sxs2473** [iBreaker/bjguahao#59]
macos 的 SIP 导致 ~/Library/Messages 默认是不给权限的
如果用 iMessage 读验证码遇到了抛异常“找不到短信数据库”，就是权限问题。
这个用 sudu 也不管用。需要
1. cmd+R 进入恢复模式。
2. 打开 terminal 执行 csrutil disable。

**Comment by iBreaker** [comment]
感谢

**Comment by Taka152** [comment]
今天使用也遇到了，@sxs2473的方法有点麻烦，给一下我的解决方案
1. 操作系统：Catalina
2. 软件：iterm2

给iterm2添加完全磁盘访问权限
![image](https://user-images.githubusercontent.com/18254977/68082623-040d4100-fe5a-11e9-93f7-996f85245918.png)
