### ISSUE TITLE
无法登陆，用户名不存在

### ISSUE THREAD

**Issue by wxhqw** [iBreaker/bjguahao#62]
Fri, 12 Oct 2018 16:50:05 bjguahao.py[line:75] INFO 配置加载完成
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:343] INFO 今日可挂号到: 2018-10-19
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:353] INFO 放号时间: 2018-10-12 07:00
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:173] INFO cookies登录失败
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:174] INFO 开始使用账号密码登陆
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:194] ERROR 用户不存在!
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:198] ERROR 
Fri, 12 Oct 2018 16:50:06 bjguahao.py[line:199] ERROR 登陆失败

**Comment by iBreaker** [comment]
这个问题11月11号已经解决了
