### ISSUE TITLE
re-login check during long term running

### ISSUE THREAD

**Issue by Radar3** [iBreaker/bjguahao#68]
may be logout after running for a long time

**Comment by iBreaker** [comment]
def lazy(self):
        cur_time = datetime.datetime.now() + datetime.timedelta(seconds=int(time.timezone + 8*60*60))
        if self.start_time > cur_time:
            seconds = (self.start_time - cur_time).total_seconds()
            logging.info("距离放号时间还有" + str(seconds) + "秒")
            sleep_time = seconds - 60
            if sleep_time > 0:
                logging.info("程序休眠" + str(sleep_time) + "秒后开始运行")
                time.sleep(sleep_time)
                # 自动重新登录
                self.auth_login()

**Comment by iBreaker** [comment]
有重新登录代码    你运行的时候没有起作用吗？
