### ISSUE TITLE
指定医生

### ISSUE THREAD

**Issue by JanonWang** [iBreaker/bjguahao#74]
现在通过114平台还能指定医生吗？114上面不是只能指定医生级别嘛，不能指定医生姓名

**Comment by huangbiubiu** [comment]
如果网页上是`副主任医师 副主任医师`，那医生姓名就是`副主任医师`

**Comment by iBreaker** [comment]
> 现在通过114平台还能指定医生吗？114上面不是只能指定医生级别嘛，不能指定医生姓名

首先，挂号助手不是通过114平台挂号，是【北京市预约挂号统一平台】。

其次，以北京市预约挂号统一平台页面上显示的为准，有可能是副主任医师这样的职称，也有可能是医生姓名。每个医院科室结果不一样。先到自己要挂的号的页面看清楚，然后写到配置文件里就可以
