### ISSUE TITLE
建议加一个参数控制挂号顺序

### ISSUE THREAD

**Issue by Bluekezhou** [iBreaker/bjguahao#75]
最近想去北医三拔牙，就想约个普通号。目前的策略是默认选最好的，但我的话就希望随便挂个号就可以了

**Comment by iBreaker** [comment]
> 最近想去北医三拔牙，就想约个普通号。目前的策略是默认选最好的，但我的话就希望随便挂个号就可以了
好的

**Comment by iBreaker** [comment]
感谢
