### ISSUE TITLE
能否增加一个指定新的预约时间的方法？

### ISSUE THREAD

**Issue by Bluekezhou** [iBreaker/bjguahao#77]
通常挂号都是提前七天左右，那么如果今天失败了，明天再尝试的话就必须修改config。
但如果把挂号日期设定为类似"+7"（表示7天之后）之类的规则，就可以直接运行程序，而不用修改config文件了。

**Comment by yiqian987** [comment]
挂号日期写 latest 自动挂最新的一个可挂日期
@iBreaker 这个issue我觉得可以关了

**Comment by Bluekezhou** [comment]
可以在readme里面提示一下，不然还得去看代码
