### ISSUE TITLE
网页改版patient_id获取逻辑变更，建议填加手动输入接口

### ISSUE THREAD

**Issue by yangyang0477** [iBreaker/bjguahao#83]
5.10号网页应该进行了改版，通过就诊人姓名获取patient_id的逻辑出现错误，可以config中填增加手动填加patient_id接口，用户可以在就诊人管理页面，删除按钮那边获取patient_id，相对比较稳定。当然也可以重新按照新逻辑抽取patient_id

**Comment by iBreaker** [comment]
感谢

**Comment by xaxfan** [comment]
您好，请问在哪里看patient_id呢，我在114网页，就诊人管理页面没有看到
