### ISSUE TITLE
求脚本，想去拔智齿，我可以留学校邮箱TvT

### ISSUE THREAD

**Issue by LiXianyao** [iBreaker/bjguahao#86]
RT，在论坛扒拔牙经验贴看到的链接，然而这算命运做人嘛正好删了=、=前辈救我，邮箱wayne_li@bupt.edu.cn 。

**Comment by iBreaker** [comment]
已发送

**Comment by LiXianyao** [comment]
收到了，感激不尽！！

**Comment by LiXianyao** [comment]
到www.114yygh.com上注册了账号和密码，然而使用脚本后总是提示“登录失败,用户名或密码错误!”，来回check了几次也没填错啊……还是我自己的问题吗orz
![image](https://user-images.githubusercontent.com/26064539/60149760-6305de00-9808-11e9-8888-fa5779bfa642.png)

**Comment by lizongkai-big** [comment]
求发脚本 spring@bupt.edu.cn

**Comment by LiXianyao** [comment]
昨晚无意中发现好像是PC网页版和微信公众号版的账号密码不互通=、=重新再微信公众号注册后可以用了，打搅了

**Comment by LiXianyao** [comment]
> 求发脚本 spring@bupt.edu.cn

已转发

**Comment by webkws** [comment]
> > 求发脚本 [spring@bupt.edu.cn](mailto:spring@bupt.edu.cn)
> 
> 已转发

求转发！2369990270@qq.com

**Comment by SunApriloy** [comment]
> RT，在论坛扒拔牙经验贴看到的链接，然而这算命运做人嘛正好删了=、=前辈救我，邮箱[wayne_li@bupt.edu.cn](mailto:wayne_li@bupt.edu.cn) 。

我也要拔牙，最近挂不上号，疫情期间太难了。请问能发我一份吗？感激不尽。xiaosunyuang@126.com
