### ISSUE TITLE
能给我发一份吗？

### ISSUE THREAD

**Issue by pyemon** [iBreaker/bjguahao#88]
非黄牛， 就是自用，挂号太难了~~~
邮箱：dingzhuhit@163.com

**Comment by wanglei5212749** [comment]
学生党，想拔个牙，一致约不上。能将code给我发一份（290979891@qq.com）吗，谢谢您。

**Comment by iBreaker** [comment]
------------------ 原始邮件 ------------------
发件人: "wanglei5212749"<notifications@github.com>;
发送时间: 2019年7月22日(星期一) 上午9:39
收件人: "iBreaker/bjguahao"<bjguahao@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [iBreaker/bjguahao] 能给我发一份吗？ (#88)




学生党，想拔个牙，一致约不上。能将code给我发一份（290979891@qq.com）吗，谢谢您。

**Comment by iBreaker** [comment]
两位, 已发送

**Comment by marsws** [comment]
老哥    谢谢你的辛勤工作，网上找了个fork版的，除了获取message不成功，别的我修好了，求发一份能用的，我参考下，谢谢，给女朋友看牙用 228624642@qq.com

**Comment by iBreaker** [comment]
------------------ 原始邮件 ------------------
发件人: marsws <notifications@github.com>
发送时间: 2019年8月15日 10:34
收件人: iBreaker/bjguahao <bjguahao@noreply.github.com>
抄送: Breaker <791628659@qq.com>, State change <state_change@noreply.github.com>
主题: 回复：[iBreaker/bjguahao] 能给我发一份吗？ (#88)




老哥    谢谢你的辛勤工作，网上找了个fork版的，除了获取message不成功，别的我修好了，求发一份能用的，我参考下，谢谢，给女朋友看牙用 228624642@qq.com

**Comment by Liuzhj** [comment]
老哥，可以发一份code吗，需要去医院拨智齿挂不上号，感激不尽，非黄牛，邮箱zhupan208@163.com

**Comment by iBreaker** [comment]
已经不在维护了，就代码也已经不能使用



------------------ 原始邮件 ------------------
发件人: Zhijie <notifications@github.com&gt;
发送时间: 2020年1月9日 22:33
收件人: iBreaker/bjguahao <bjguahao@noreply.github.com&gt;
抄送: Breaker <791628659@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[iBreaker/bjguahao] 能给我发一份吗？ (#88)




老哥，可以发一份code吗，需要去医院拨智齿挂不上号，感激不尽，非黄牛，邮箱zhupan208@163.com
