### ISSUE TITLE
dutyCode参数修改为支持全天

### ISSUE THREAD

**Issue by iBreaker** [iBreaker/bjguahao#9]
dutyCode参数修改为支持全天

**Comment by yiqian987** [comment]
支持全天挂号和医保类型好没开发完吧，看了最新的代码，写的逻辑是越来越好啦

**Comment by iBreaker** [comment]
还没有呢~~   现在只可以选上午下午

**Comment by yiqian987** [comment]
配置中的patientName 是中文名字还是病人id？

**Comment by iBreaker** [comment]
patientName  填入中文名字

**Comment by yaoyitong** [comment]
你好，想试着直接运行下你的代码看看结果。我运行的是bjguahao.py，然后报错说是
  File "log.py", line 63, in info
    print("\033[0;37m " + Log.get_time()  + " [info] " + msg  + "\033[0m")

LookupError: unknown encoding: cp0

请问该如何解决呢？config文件中我都有修改

**Comment by iBreaker** [comment]
发件人：yaoyitong <notifications@github.com> 
时　间：2017年3月26日(星期天) 凌晨1:11 (UTC-07:00 休斯顿、底特律时间)
主　题：Re: [iBreaker/bjguahao] dutyCode参数修改为支持全天 (#9)
收件人：	iBreaker/bjguahao <bjguahao@noreply.github.com>
抄　送：	Breaker <791628659@qq.com>; Assign <assign@noreply.github.com>
 yaoyitong 将 iBreaker/bjguahao、Breaker、Assign 加入此次会话
 
你好，想试着直接运行下你的代码看看结果。我运行的是bjguahao.py，然后报错说是
File "log.py", line 63, in info
print("\033[0;37m " + Log.get_time() + " [info] " + msg + "\033[0m")

LookupError: unknown encoding: cp0

请问该如何解决呢？config文件中我都有修改

**Comment by iBreaker** [comment]
收到一封邮件

**Comment by iBreaker** [comment]
你好  
 请提供你的运行环境

OS:
python版本
运行的是那一个分支:



791628659@qq.com
 
发件人： yaoyitong
发送时间： 2017-03-26 16:11
收件人： iBreaker/bjguahao
抄送： Breaker; Assign
主题： Re: [iBreaker/bjguahao] dutyCode参数修改为支持全天 (#9)
你好，想试着直接运行下你的代码看看结果。我运行的是bjguahao.py，然后报错说是
File "log.py", line 63, in info
print("\033[0;37m " + Log.get_time() + " [info] " + msg + "\033[0m")
LookupError: unknown encoding: cp0
请问该如何解决呢？config文件中我都有修改

**Comment by yaoyitong** [comment]
您好，我是在spider下运行会这样报错，但是在cmd下就可以正常运行，不懂这是为什么，请问您能指点一二吗？

**Comment by iBreaker** [comment]
你可以说的清楚点吗？具体是什么环境
操作系统版本、python版本、在哪个分支运行、以及你的那个spider是什么

**Comment by yaoyitong** [comment]
操作系统是win7，python2.7，哦抱歉打错了，是spyder这个IDE下运行的。我直接运行的是bjguahao.py，然后提示 在log.py里报错。。
File "log.py", line 63, in info
print("\033[0;37m " + Log.get_time() + " [info] " + msg + "\033[0m")
LookupError: unknown encoding: cp0

**Comment by iBreaker** [comment]
是master分支的代码吗？如果是master分支的代码。请切换到dev分支运行，看看有没有报错
