### ISSUE TITLE
请求一份exe版，谢谢

### ISSUE THREAD

**Issue by samzzzz** [iBreaker/bjguahao#90]
邮箱raxray.man@gmail.com，感谢，想研究研究。
不忍心老爸凌晨去排队挂还总挂不上，读了大神的代码，pythone3已运行成功，只挂指定医生的号，把优选医生注释掉了，感谢。

**Comment by iBreaker** [comment]
https://github.com/iBreaker/bjguahao/releases/tag/v1.0.8
