### ISSUE TITLE
Qpython error -- "No module named Crypto"

### ISSUE THREAD

**Issue by JanonWang** [iBreaker/bjguahao#92]
我在手机上装了Qpython、Qpython3以及Qpy3.6。在运行qpython3_run.py之后，报错如下。
已经安装了crypto的库，但还是报错。
google了解决方案，尝试安装pycrypto，但是未安装成功。
![image](https://user-images.githubusercontent.com/15688830/64087119-345b3500-cd6e-11e9-9f59-04ee86ce9677.png)

请问大家有遇到类似的问题吗？

**Comment by caohm** [comment]
![图片](https://user-images.githubusercontent.com/5270621/64219281-7368c200-cef7-11e9-9ff6-c722b672c496.png)
同样问题
手机：huawei p30 
Python：3.6.6
网络：联通4G
