### ISSUE TITLE
windows 安装程序

### ISSUE THREAD

**Issue by gifzlh** [iBreaker/bjguahao#95]
您好，请问哪里可以下载Windows的安装程序使用，谢谢!

**Comment by iBreaker** [comment]
https://github.com/iBreaker/bjguahao/releases/tag/v1.0.8

**Comment by gifzlh** [comment]
非常感谢，因为家人身体不太好，一直想挂北医三院的号。您能帮我看下手机版报这个错误是什么问题吗，感恩。
PS:QPython3和QPython3从谷歌商店下载的，qpy因为商店里下架了，然后从github项目qpython-android下载的。

Breaker <notifications@github.com> 於 2019年9月11日週三 16:56寫道：

**Comment by gifzlh** [comment]
QPython3和QPython从谷歌商店下载的，qy3.6从github下载的，谢谢。

Breaker <notifications@github.com> 於 2019年9月11日週三 16:56寫道：
