### ISSUE TITLE
关于手机版报错，盼复，谢谢！

### ISSUE THREAD

**Issue by gifzlh** [iBreaker/bjguahao#97]
非常感谢您提供windows程序，因为媳妇习惯性流产，一直想挂北医三院和协和的号。您能帮我看下手机版报这个错误是什么问题吗，感恩。
 PS:QPython3和QPython从谷歌商店下载的，qpy3.6因为商店里下架了，然后从github项目qpython-android下载的，我试了下运行项目内置的脚本，同样报错，大概率是我手机问题。
项目手机版报错截图
![Screenshot_2019-09-12-20-15-17-32](https://user-images.githubusercontent.com/34907350/64783854-6012c200-d59b-11e9-9ad3-f44a9beedb42.png)
项目内置脚本报错截图
![Screenshot_2019-09-12-20-16-00-85](https://user-images.githubusercontent.com/34907350/64783963-a405c700-d59b-11e9-81ef-a7d0aa5d8bf1.png)
手机系统配置截图
![IMG_20190912_202214](https://user-images.githubusercontent.com/34907350/64783999-b2ec7980-d59b-11e9-86a8-429f1505dd4b.jpg)
期盼回复，万分感谢！

**Comment by iBreaker** [comment]
换个网络环境试试？

**Comment by gifzlh** [comment]
你好，我来数据试过也不行。

Breaker <notifications@github.com> 於 2019年9月16日週一 16:48寫道：

**Comment by iBreaker** [comment]
看看是不是权限的问题，是你手机本身的问题

**Comment by gifzlh** [comment]
恩 我也怀疑是手机问题 因为我运行项目自带的脚本也报同样错误

Breaker <notifications@github.com> 於 2019年9月19日週四 16:42寫道：

**Comment by gifzlh** [comment]
恩，感谢您耐心解答，我开始也怀疑过权限和手机代理软件通道问题，我试了xprivacy给全部权限，supersu已授权，代理软件也将3个软件全部加入不走代理名单。可能就是我这破手机不适配了，我能想的问题都想了。

章鱼 <zhangyu80112@gmail.com> 於 2019年9月19日週四 17:04寫道：

**Comment by gifzlh** [comment]
数据网络和wifi都试过了😅

章鱼 <zhangyu80112@gmail.com> 於 2019年9月19日週四 17:04寫道：
