### ISSUE TITLE
config.yaml文件里password的该怎么填写

### ISSUE THREAD

**Issue by IvyGongoogle** [iBreaker/bjguahao#98]
您好，有个问题不明白，请问config.yaml中password该怎么填写呢，现在114平台网页登录填写手机号和手机收到的验证码就行，没有密码呀。。。   该怎么办？
 
 
 
谢谢

**Comment by fa1247** [comment]
曾经可以密码登陆，现在只能通过验证码，所以password选项应该失效，不用写。
